services:
  nginx: # Add the Nginx reverse proxy
    build: ./nginx  # Build from the Dockerfile in the ./nginx directory
    ports:
      - "80:80"   # Expose port 80 on the host
    depends_on:
      - frontend
      - authentication
      - user
      - bookcatalogue
      - wishlist

  consul:
    image: consul:1.15.3  # This was already using a Docker Hub image
    ports:
      - "8500:8500"
    command: "agent -dev -client=0.0.0.0 -log-level=info"

  postgres:
    image: 'postgres'
    environment:
      - 'POSTGRES_USER=eazybook_dbuser'
      - 'POSTGRES_PASSWORD=eazybook_dbpassword'
      - 'POSTGRES_DB=eazybooks'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  authentication:
    image: lanreoreyomi/authentication:local-v1.2
    ports:
      - "9084:9084"
    depends_on:
      - consul
      - postgres
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/eazybooks
      - SPRING_DATASOURCE_USERNAME=eazybook_dbuser
      - SPRING_DATASOURCE_PASSWORD=eazybook_dbpassword
      - SPRING_PROFILES_ACTIVE=local
    restart: on-failure

  user:
    image: lanreoreyomi/user:local-v1.2 # Use the Docker Hub image
    ports:
      - "9087:9087"
    depends_on:
      - consul
      - postgres
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/eazybooks
      - SPRING_DATASOURCE_USERNAME=eazybook_dbuser
      - SPRING_DATASOURCE_PASSWORD=eazybook_dbpassword
    restart: on-failure

  bookcatalogue:
    image:  lanreoreyomi/bookcatalogue:local-v1.2 # Use the Docker Hub image
    ports:
      - "9189:9189"
    depends_on:
      - consul
      - postgres
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/eazybooks
      - SPRING_DATASOURCE_USERNAME=eazybook_dbuser
      - SPRING_DATASOURCE_PASSWORD=eazybook_dbpassword
    restart: on-failure

  wishlist:
    image: lanreoreyomi/wishlist:local-v1.2 # Use the Docker Hub image
    ports:
      - "8017:8017"
    depends_on:
      - consul
      - postgres
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/eazybooks
      - SPRING_DATASOURCE_USERNAME=eazybook_dbuser
      - SPRING_DATASOURCE_PASSWORD=eazybook_dbpassword
    restart: on-failure

  frontend:
    image: lanreoreyomi/frontend:local-v1.2
    environment:
      - VITE_APP_API_BASE_URL=http://localhost
    depends_on:
      - authentication
      - user
      - bookcatalogue
      - wishlist

volumes:
  postgres_data: